# Generated by Django 5.0.1 on 2024-01-23 18:45

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('cmob', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(\\+\\d{1,3}[- ]?)?\\d{10}$', message='Only numbers allowed'), django.core.validators.MinLengthValidator(10, '10-digit allowed')])),
                ('cdate', models.DateField(default=datetime.date.today)),
                ('cemail', models.EmailField(max_length=254)),
                ('cmsg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\S[0-9]{0,3}$')])),
                ('mob_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(\\+\\d{1,3}[- ]?)?\\d{10}$', message='Only numbers allowed'), django.core.validators.MinLengthValidator(10, '10-digit allowed')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans', 'Trans')], max_length=20)),
                ('speciality', models.CharField(choices=[('Orthopedics', 'Orthopedics'), ('Internal Medicine', 'Internal Medicine'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Radiology', 'Radiology'), ('General Surgery', 'General Surgery'), ('Ophthalmology', 'Ophthalmology')], max_length=100)),
                ('date_of_join', models.DateField()),
                ('salary', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientAppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('patient_mob', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(\\+\\d{1,3}[- ]?)?\\d{10}$', message='Only numbers allowed'), django.core.validators.MinLengthValidator(10, '10-digit allowed')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans', 'Trans')], max_length=20)),
                ('age', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\S[0-9]{0,3}$')])),
                ('address', models.TextField()),
                ('date_appo', models.DateField()),
                ('status', models.CharField(default='pending', max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Admit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=5)),
                ('contact_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(\\+\\d{1,3}[- ]?)?\\d{10}$', message='Only numbers allowed'), django.core.validators.MinLengthValidator(10, '10-digit allowed')])),
                ('age', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\S[0-9]{0,3}$')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans', 'Trans')], max_length=20)),
                ('address', models.TextField()),
                ('admit_date', models.DateField(default=datetime.date.today)),
                ('discharge_date', models.DateField(default=datetime.date.today)),
                ('deposite_fee', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patientappo')),
            ],
        ),
    ]
